### ISSUE TITLE
TV Shows don't work anymore

### ISSUE THREAD

**Issue by enlivendreamer** [YoColdRain/Hotstar-Rain#11]
Don't know if this is due to the latest update or if something has changed on hotstar, but the trying to play latest tv shows doesn't work anymore (Think from the past 3-4 days, which coincides with the latest update).

**Comment by YoColdRain** [comment]
See, thats why you should use forum thread instead of posting here, so everyone else can verify if this is any true.  You've given me no way to debug your issue.  Please find forum thread, google it.
