### ISSUE TITLE
Live Streaming Problem

### ISSUE THREAD

**Issue by manojgadde** [YoColdRain/Hotstar-Rain#14]
Live Streaming from hotstar is not working. please add it as soon as possible

**Comment by YoColdRain** [comment]
sorry, I never worked on live stream part because I never had access to premium account which is required for live stream also needed VPN which I never had.

**Comment by manojgadde** [comment]
i'm not asking about premium live streaming. but there are channels like republic tv & sky news live streaming for all users. please find a way for that.
