### ISSUE TITLE
Need for interface to gain access to other languages

### ISSUE THREAD

**Issue by avinashkumarcse** [YoColdRain/Hotstar-Rain#9]
I cannot access or fetch the movie list of other languages such as Kannada or Telugu. Current app lists only hindi movies. Need for interface to gain access to other languages.

**Comment by YoColdRain** [comment]
Avinash, please don't post ideas on github, post then under forum thread on kodi forums.  
I have fixed search, just need to push it, and for other languages check add-on settings for language changes.  You would know about this is you look at the forum thread.
